### ISSUE TITLE
New Video: Materials Science - Muon Spectroscopy

### ISSUE THREAD

**Issue by shiltemann** [gallantries/video-library#112]
@leandro-liborio Thanks a lot for your video submission! I have added it to the video library.

We just need you to have a quick look at the captions document and fix them up (instructions in the doc):
https://docs.google.com/document/d/1QDOdldEH4QzuNIsxrNjcj0yu8w3F6eJJjSY2cKg-trA/edit?usp=sharing

please ping me here when you complete them, and I will copy them over to YouTube :)

P.S. You've got some nice slides there, how would you feel about adding those to the GTN as well?

**Comment by leandro-liborio** [comment]
Hi Saskia,

Thanks for your message.

I have already gone through the captions and edited them.

This video is already part of a tutorial in the GTN (
https://training.galaxyproject.org/training-material/topics/materials-science/tutorials/muon-stopping-sites-muairss-uep/tutorial.html
)

That tutorial is organised around the video lecture.

Regards,

Leandro

**Comment by shiltemann** [comment]
Hi @leandro-liborio thanks a lot for doing the captions, I have added them to to the video.

> That tutorial is organised around the video lecture

That is great, I was just wondering if you were willing to share your slide deck so that it can be added to the GTN, this would make it easier to make changes in the future (since we can also generate automated video slides from slide decks and speaker notes), and also would enable other educators to reuse your slides for their own trainings. Let me know what you think. 

> This video is already part of a tutorial in the GTN

Yep, as soon as it is added in this repo, the connection to the GTN is automatically made. Let me know if anything on the [video page](https://gallantries.github.io/video-library/videos/materials-science/muon-stopping-sites-muairss-uep/) needs to change. For example, I did not add a description yet, but if you have a few lines you would like to add about what the video covers please let me know :)

Thanks a lot for your contribution!
