### ISSUE TITLE
[New] Pangeo Climate Tutorials

### ISSUE THREAD

**Issue by hexylena** [gallantries/video-library#31]
@annefou indicated she wishes to have a couple new climate tutorials added and ready for Smörgåsbord 2.

- https://github.com/NordicESMhub/galaxy-training-material/tree/pangeo/topics/climate/tutorials/pangeo 
- https://github.com/NordicESMhub/galaxy-training-material/tree/pangeo/topics/climate/tutorials/pangeo-notebook

Here are the items which need to be completed and the dates they need to be done by

- [x] **Feb 28** Merge to GTN
- [x] **Feb 28**: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link) @annefou 
- [x] **Feb 30**: @gallantries send captions to @annefou
- [x] **Mar 7**: Captions due - @annefou
- [x] **Mar 8**: Captions live - @gallantries

**Comment by hexylena** [comment]
Just checking in @annefou, is there anything you need from us before submitting your video? :)

**Comment by annefou** [comment]
> Just checking in @annefou, is there anything you need from us before submitting your video? :)

No, I don't think so.  I am planning to record them over the weekend. So hopefully I will be on time! I cannot work on it before.

**Comment by hexylena** [comment]
Sounds great! Looking forward to it :)

**Comment by hexylena** [comment]
Hi @annefou the captions are ready for your review/editing! https://docs.google.com/document/d/1gswxyp7dfQNA8V3PWdUxVVnKjFnr-kSasdogkktn-rI/edit

**Comment by annefou** [comment]
> Hi @annefou the captions are ready for your review/editing! https://docs.google.com/document/d/1gswxyp7dfQNA8V3PWdUxVVnKjFnr-kSasdogkktn-rI/edit

I fixed captions, etc. Thanks!

**Comment by hexylena** [comment]
Live in a7cb020cae62f400e64cd472c2477c22af512472, fantastic @annefou !

**Comment by hexylena** [comment]
https://docs.google.com/document/d/1jjPa9p8SxPZ9XD5mTxg9FMgxUC19guUdXGtB0jlE2Cw/edit ok last set of captions, sorry for the delay!

**Comment by annefou** [comment]
@hexylena Don't worry. I know you are extremely busy these days so I really appreciate your work! I fixed the captions. Many thanks.
