### ISSUE TITLE
[New] Bulk RNA Deconvolution with MuSiC

### ISSUE THREAD

**Issue by hexylena** [gallantries/video-library#33]
@mtekman, @nomadscientist will be contributing a video for

"Bulk RNA Deconvolution with MuSiC
https://github.com/galaxyproject/training-material/pull/2790"

Here are the items which need to be completed and the dates they need to be done by

- [x] **Feb 28** Merge to GTN
- [x] **Feb 28**: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link) @mtekman, @nomadscientist 
- [x] **Feb 30**: @gallantries send captions to @mtekman, @nomadscientist
- [x] **Mar 7**: Captions due - @mtekman, @nomadscientist
- [x] **Mar 8**: Captions live - @gallantries

**Comment by hexylena** [comment]
Just checking in @mtekman, @nomadscientist, is there anything you need from us before submitting your video? :)

**Comment by hexylena** [comment]
Discussed out of band, @nomadscientist was on holiday, pending her return.

**Comment by nomadscientist** [comment]
You guys with your google forms! You are geniuses! Submitted now

**Comment by hexylena** [comment]
https://docs.google.com/document/d/1Om8q_fY8KU_peeTSogmgaTlC29VnQ_8CUCjIg8KjmYM/edit captions ready!

**Comment by mtekman** [comment]
@hexylena lmao at the title :P

**Comment by hexylena** [comment]
it's such a silly software acronym, MuSiC! I couldn't resist :p

**Comment by nomadscientist** [comment]
@hexylena Captions done!

**Comment by hexylena** [comment]
Amazing!

**Comment by hexylena** [comment]
Fantastic! Captions are live.

What is the correct ordering within this module?
https://gallantries.github.io/video-library/modules/single-cell
Where does bulk-music go? 

Do you need sections? How should that page look?

Otherwise I'm closing this issue since all of the tasks are DONE

**Comment by mtekman** [comment]
@hexylena it looks fine to me, deconvolution is a complimentary analysis after both RNA and scRNA, so it should go at the end -- thanks for taking care of all

@nomadscientist cheers for finishing the captions! I got distracted this week
