### ISSUE TITLE
[New] Fruit 360

### ISSUE THREAD

**Issue by hexylena** [gallantries/video-library#34]
@kxk302 indicated will make a video for https://training.galaxyproject.org/training-material/topics/statistics/tutorials/fruit_360/tutorial.html, awesome!

Here are the items which need to be completed and the dates they need to be done by

- [x] **Feb 28** Merge to GTN
- [x] **Feb 28**: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link) @kxk302 
- [x] uploaded to youtube EX8gZ1lxhNY
- [x] **Feb 30**: @gallantries send [captions](https://docs.google.com/document/d/1i7TDnoDk10lO2qQnW4hl37eFnRlnTV4J_ZaCadnF6IA/edit ) to @kxk302
- [x] **Mar 7**: Captions due - @kxk302
- [x] **Mar 8**: Captions live - @gallantries

**Comment by kxk302** [comment]
Thanks @hexylena, I'll record a Zoom video and will submit it soon.

**Comment by hexylena** [comment]
Hi @kxk302 the captions are ready! You can find them here to correct them: https://docs.google.com/document/d/1i7TDnoDk10lO2qQnW4hl37eFnRlnTV4J_ZaCadnF6IA/edit

**Comment by kxk302** [comment]
@hexylena I completed the captions. Could you please merge this so the video becomes available on GTN website? Thank you!

**Comment by hexylena** [comment]
I've added the video the library now https://github.com/gallantries/video-library/commit/7ac126e2b8b0eadab8420a04f0266a3206534a43 it will show up on the GTN during the next deployment of the GTN. (Which is never too far away)

**Comment by hexylena** [comment]
Thanks so much @kxk302 !! This is fantastic

**Comment by kxk302** [comment]
> Thanks so much @kxk302 !! This is fantastic

Thanks @hexylena!
