### ISSUE TITLE
[New] Tool development

### ISSUE THREAD

**Issue by hexylena** [gallantries/video-library#35]
@gallardoalba indicated he will add a new video on Tool Developement

Here are the items which need to be completed and the dates they need to be done by

- [x] **Feb 28** Merge to GTN
- [x] **Feb 28**: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link) @gallardoalba 
- [x] **Feb 30**: @gallantries send captions to @gallardoalba
- [x] **Mar 7**: Captions due - @gallardoalba
- [x] **Mar 8**: Captions live - @gallantries

**Comment by hexylena** [comment]
@gallardoalba just checking in :) Are you submitting a new tutorial or just re-recording the existing one? (Either way is great! Just want to check if there's something I need to merge first or if I can check the first box off.)

**Comment by gallardoalba** [comment]
Hi! Finally, I will re-record the existing one.

**Comment by hexylena** [comment]
Hey @gallardoalba following up on this to see if there's anything you need, or when you expect to have this done, or if we should drop it from the schedule :)

**Comment by gallardoalba** [comment]
Hi @hexylena, I'll record this along the weekend. Regards!

**Comment by gallardoalba** [comment]
HI @hexylena, I'll finish everything for Thursday if it is fine for you. Really sorry for the delay, I have been a bit dispersed last weeks.

**Comment by hexylena** [comment]
@gallardoalba thanks for the update! We really appreciate it!
