### ISSUE TITLE
[New] Funanotate, RepeatMasker

### ISSUE THREAD

**Issue by hexylena** [gallantries/video-library#38]
Thanks @abretaud for having interest in these. Here are the dates

**RepeatMasker**

- [x] **Feb 28** [Tutorials are in the GTN](https://github.com/galaxyproject/training-material/pull/3146)
- [x] **Feb 28**: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link)
- [x] **Feb 30**: @gallantries send captions to
- [x] **Mar 7**: Captions due - @abretaud @hexylena 
- [x] **Mar 8**: Captions live - @gallantries 
- [x] Live on website

**Funanotate**

- [x] **Feb 28** [Tutorials are in the GTN](https://github.com/galaxyproject/training-material/pull/3146)
- [x] **Feb 28**: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link)
- [x] **Feb 30**: @gallantries send captions to
- [x] **Mar 7**: Captions due - @abretaud @hexylena 
- [x] **Mar 8**: Captions live - @gallantries 
- [x] Live on Website

**Comment by abretaud** [comment]
Currently updating the funannotate tutorial with newer eggnog+interproscan (it should fix a problem in the final output at the end of the tuto)

**Comment by hexylena** [comment]
Hey @abretaud anything you need from us before recording the video? Any of the videos you want me to do?

**Comment by abretaud** [comment]
Hey!
The tuto is ready, and tested on usegalaxy.eu and .fr :heavy_check_mark: 
It's being installed on .org.au (some data manager stuff to run still), and [there's a PR for .org](https://github.com/galaxyproject/usegalaxy-tools/pull/473), but it's not blocking as it works on .eu.
I just need to record stuff now :) I think I'll have time to do it all, I guess it's easier for me to do it since I know the content quite well now... *But* is it ok if I upload it a few days late (=sometime next week)?

**Comment by abretaud** [comment]
First video (Repeat Masking) sent :heavy_check_mark:

**Comment by hexylena** [comment]
Uploaded, awaiting youtube to caption. :ballot_box_with_check:

**Comment by hexylena** [comment]
RepeatMasker Captions ready for correction: https://docs.google.com/document/d/1K_hSmApju451aiVYYquMEA0ZzekibtMIaYvBme36kHw/edit

**Comment by abretaud** [comment]
Captions are corrected now :)
I will probably prepare the next video this afternoon

**Comment by abretaud** [comment]
Funannotate video recorded :heavy_check_mark: :tada: 
I'll clean it up / upload it tomorrow (+ make a small change to the tuto)

**Comment by hexylena** [comment]
Repeatmasker live on the website.

**Comment by abretaud** [comment]
Video uploaded for funannotate + made [this little PR](https://github.com/galaxyproject/training-material/pull/3216) to match the order I used in the video

**Comment by hexylena** [comment]
Awesome! Uploading to youtube now.

**Comment by hexylena** [comment]
https://docs.google.com/document/d/1cr1WyX36alsyBr-5CguhplcxVdiSIAeFunJhM98iEhA/edit funannotate captions available for review!

**Comment by abretaud** [comment]
Thanks! But that's the captions from the last chunk only apparently (all the 9 videos on my google drive are for the ame funannotate tutorial)

**Comment by hexylena** [comment]
Ok, I see what happened. In the initial submission you linked the gdrive, in the second submission I just received the link for 08-comparing

Ack. Ok, I'll download those, merge them, upload.

**Comment by abretaud** [comment]
Arf, sorry! I'll need to have a better look at the copy&paste tutorial for next time ;)

**Comment by hexylena** [comment]
Uploaded, captions generating now

**Comment by hexylena** [comment]
https://docs.google.com/document/d/1cr1WyX36alsyBr-5CguhplcxVdiSIAeFunJhM98iEhA/edit captions are fixed :( sorry @abretaud

**Comment by abretaud** [comment]
Thanks! I'll make the correction soonish

**Comment by abretaud** [comment]
Caption corrected (finally!) :ballot_box_with_check:

**Comment by hexylena** [comment]
fantastic!!!!
