### ISSUE TITLE
[New] CRISPR screen analysis

### ISSUE THREAD

**Issue by mblue9** [gallantries/video-library#40]
Copied below from the other issues here
- [x] Feb 28 Tutorials are in the GTN
- [x] Feb 28: [Record a video](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html) following our guidelines and [submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link)
- [x] Feb 30: https://github.com/gallantries send captions to
- [x] Mar 7: Captions due 
- [x] Mar 8: Captions live - https://github.com/gallantries

**Comment by hexylena** [comment]
awesome @mblue9 !! I'm so excited for this :)

**Comment by hexylena** [comment]
Hey @mblue9 just checking in since we've gone past some deadlines, do you still want to include this in this year's Tapas?

**Comment by mblue9** [comment]
Hi @hexylena yes! I'm in the middle of finishing off a few edits but will have it done this week if that's ok?

**Comment by hexylena** [comment]
Yeah no dramas ! just wanted to check in! :)

**Comment by hexylena** [comment]
aye, absolutely

**Comment by hexylena** [comment]
https://docs.google.com/document/d/1houCcc1DJv-H3cppyOMIr8EUKmaKUGBWgfpA42hlYEc/edit captions are finally available for your review!

**Comment by mblue9** [comment]
👍 Ok done, captions reviewed.

**Comment by hexylena** [comment]
Thanks so much @mblue9 can't wait to follow this session!
