### ISSUE TITLE
[New] Using Workflow Parameters

### ISSUE THREAD

**Issue by shiltemann** [gallantries/video-library#60]
@mvdbeek indicated he will record a new video, for the following training material:

- [Using Workflow Parameters](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-parameters/tutorial.html)

Here are the items which need to be completed and the dates they need to be done by

- [x] [Read the video recording guidelines](https://gallantries.github.io/video-library/events/smorgasbord2/recording.html)
- [x] Record a video!
- [x] July 1: [Submit it via google forms.](https://docs.google.com/forms/d/e/1FAIpQLSdYlHLqkt4PdY8uarkv1j01ZuWlEp5w3sGmZ1uy7N45j7ikwQ/viewform?usp=sf_link) **You**
- [x] July 2: @gallantries sends you captions.
- [x] July 7: Captions due - **You!**

**Comment by mvdbeek** [comment]
I'll need some more time but it'll happen. I can subtitle myself.

**Comment by shiltemann** [comment]
@mvdbeek great! I will upload it to the Galaxy YT channel and add it to the event webpage

**Comment by shiltemann** [comment]
@mvdbeek ok, the captions document is here: https://docs.google.com/document/d/1PTZvXXrtzbqeuq2z4vHstQ54VhXz1pqGmFgKltQqT5w/edit?usp=sharing

Thanks!

**Comment by mvdbeek** [comment]
Alright, done!

**Comment by shiltemann** [comment]
Perfect! Added them on YouTube. Closing the issue now, thanks Marius, this is great to have!
